// Tests for src/conf.h. Machine-generated by `configure` from
// src/conf.h.in; no implementation file. See
// docs/BUG_CATALOG.md#srcconfh -- no bugs found, this just confirms
// the checked-in snapshot's constants still match this platform.

#include "catch_amalgamated.hpp"

#include "conf.h"

static_assert(SIZEOF_SHORT_INT == sizeof(short), "SIZEOF_SHORT_INT mismatch");
static_assert(SIZEOF_INT == sizeof(int), "SIZEOF_INT mismatch");
static_assert(SIZEOF_LONG_INT == sizeof(long), "SIZEOF_LONG_INT mismatch");
static_assert(SIZEOF_LONG_LONG_INT == sizeof(long long), "SIZEOF_LONG_LONG_INT mismatch");

TEST_CASE("conf.h's size constants match this platform", "[conf]") {
	REQUIRE(SIZEOF_SHORT_INT == sizeof(short));
	REQUIRE(SIZEOF_INT == sizeof(int));
	REQUIRE(SIZEOF_LONG_INT == sizeof(long));
	REQUIRE(SIZEOF_LONG_LONG_INT == sizeof(long long));
}
